### PR TITLE
Add modify method to RW.

### PR DESCRIPTION
**Pull request by thejpster**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit b8fa1d1 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit b8fa1d1 with merge 9a16c9d...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/volatile-register/builds/167920975)
Approved by: japaric
Pushing 9a16c9d5ef8fce4cfdffa8834fc5247e65712a1f to master...

**Pull request merged**
