### PR TITLE
model the registers after `Cell`

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 3fbebbd has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 3fbebbd with merge 3fbebbd...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/volatile-register/builds/208830471)
Approved by: japaric
Pushing 3fbebbd33e1276086d343809ef9e547f19f0122d to master...

**Pull request merged**
