### PR TITLE
enable cache and drop target files

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit afb07d5 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit afb07d5 with merge afb07d5...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/volatile-register/builds/165708883)
Approved by: japaric
Pushing afb07d59ffb07824a12e1ab5e88ac20f880d2995 to master...

**Pull request merged**
