### PR TITLE
Travis CI

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 342ba2d with merge 342ba2d...

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 782f5bf with merge 782f5bf...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit d0c65ac has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit d0c65ac with merge d0c65ac...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/volatile-register/builds/163254053)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 6f5936c has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 6f5936c with merge 6f5936c...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/volatile-register/builds/163254603)
Approved by: japaric
Pushing 6f5936c4365647753c606fa692b8cb19acdf2af4 to master...

**Pull request merged**
