### PR TITLE
.travis: remove webhooks

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 0433e6b has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 0433e6b with merge 0433e6b...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/volatile-register/builds/174112464)
Approved by: japaric
Pushing 0433e6b5971cba22ea24c98a2827e4b73eb337ed to master...

**Pull request merged**
