### PR TITLE
CI: use the cross template

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit caa1be6 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit caa1be6 with merge caa1be6...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/volatile-register/builds/190008559)
Approved by: japaric
Pushing caa1be62b6d7d9a481d4c2ee2d18dab3ea79dd50 to master...

**Pull request merged**
